package com.telerikacademy.oop.application.commands.enums;

public enum CommandType {
    // ADD:
    ADDMEMBERTOTEAM,
    ADDCOMMENTTOWORKITEM,


    // ASSING AND UNNASSIGN
    ASSIGNWORKITEMTOMEMBER,
    UNASSIGNWORKITEM,

    // CHANGE:
    CHANGEPRIORITYOFBUG,
    CHANGEPRIORITYOFSTORY,
    CHANGERATINGOFFEEDBACK,
    CHANGESEVERITYOFBUG,
    CHANGESIZEOFSTORY,
    CHANGESTATUSOFBUG,
    CHANGESTATUSOFFEEDBACK,
    CHANGESTATUSOFSTORY,

    // CREATE
    CREATEBUG,
    CREATEFEEDBACK,
    CREATENEWBOARDINTEAM,
    CREATENEWMEMBER,
    CREATESTORY,
    CREATETEAM,

    // FILTER
    FILTERWORKITEMBYASSIGNEE,
    FILTERWORKITEMBYSTATUS,
    FILTERWORKITEMBYSTATUSANDASSIGNEE,

    // LIST
    LISTALLBUGS,
    LISTALLFEEDBACK,
    LISTALLSTORIES,
    LISTALLWORKITEMS,

    //SHOW
    SHOWALLPEOPLE,
    SHOWALLTEAMBOARDS,
    SHOWALLTEAMMEMBERS,
    SHOWALLTEAMS,
    SHOWBOARDSACTIVITY,
    SHOWPERSONACTIVITY,  //TODO
    SHOWTEAMACTIVITY,

    //SORT
    SORTWORKITEMSBYPRIORITY,
    SORTWORKITEMSBYSEVERIRY,
    SORTWORKITEMSBYTITLE,
    SORTWORKITEMSBYSIZE,
    SORTWORKITEMSBYRATING;
}